
# Site settings
url: "http://parcbotannia.com/"
name : Parc Botannia
brand : Parc Botannia
description : This is the description of my project
keyword :
year : 2016
logo-url: "img/parcbotannia_logo.svg"
exclude :
  - node_modules

#Sass
sass:
  style: compressed
